[package]
name = "aruna_cache"
version = "0.1.0"
edition = "2021"
description = "A library to cache resources for AOS"
repository = "https://github.com/ArunaStorage/aruna-cache"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
diesel-ulid = "0.2.0"